webelopers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Main import views
from webelopers import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.login_),
    path('setmeeting/', views.setmeeting),
    path('logout/', views.logout_),
    path('signup/', views.signup),
    path('profile/', views.profile),
    path('profile/<str:username>', views.profile),
    path('editprofile/', views.editprofile),
    path('contact', views.contact),
    path('removeuser', views.removeuser),
    path('search_teachers_api/', views.json_query),
] + static(settings.STATIC_URL, document_root=settings.SITE_ROOT)

Main/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime

class Person(models.Model):
    GENDER_CHOICES = (
        ("M", "مرد"),
        ("F", "زن")
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, default="M")
    picture = models.FileField(upload_to="static/pictures/", null=True, blank=True)


class Meeting(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    capacity = models.IntegerField(default=0)
    start = models.TimeField()
    end = models.TimeField()
    date = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Teacher Free Times"

templates/base_html.html
<!DOCTYPE html>
<html lang="fa">
    <head>
        <meta charset="UTF-8">
        <title>ثبت نام</title>
        <link rel="stylesheet" href="https://cdn.rtlcss.com/semantic-ui/2.2.6/semantic.rtl.css" integrity="sha384-h/tGiTStmgbDQyTAdp2s5BfyXn7wmnFsn3vDaCPYck9YKkOuLAdjHi6y154TBVJ4" crossorigin="anonymous">
        <script src="https://cdn.rtlcss.com/semantic-ui/2.2.6/semantic.min.js" integrity="sha384-kZT+CItOKWHYL+Rz37W2NEz60Pu2JJJ8wgzq+82VWsi3QM53eNFzQJZqzhPuyo63" crossorigin="anonymous"></script>
    </head>
    <body dir="rtl">
        <nav class="ui pointing menu rtl" id="id_navbar">
            <a class="item" href="/" id=id_navbar_home>صفحه اصلی</a>

            {% if user.is_authenticated == False %}
            <a class="item" href="/signup" id=id_navbar_signup>ثبت نام</a>
            <a class="item" href="/login" id=id_navbar_login>ورود</a>
            {% endif %}
                {% if group == 'استاد' %}
                    <a class="item" href="/setmeeting" id=id_navbar_meeting>ایجاد فرصت ملاقات</a>
                {% endif %}
                <a class="item" href="/logout" id=id_navbar_logout>خروج</a>
                <a class="item" href="/profile" id=id_navbar_profile>پروفایل</a>
                <a class="item" href="/editprofile" id=id_edit_profile>ویرایش پروفایل</a>
            <a class="item" href="/contact" id=id_navbar_contact_us>تماس  با ما</a>
            <div class="right menu">
                <div class="item">
                    <div class="ui transparent icon input">
                        <form action="/" method="get">
                            {% csrf_token %}
                            <input type="text" name="search" id="id_search_profiles_input" placeholder="جستجو..."/>
                            <button id="id_search_profiles_button" >جستجو</button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
        <div class="ui segment">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/contactus.html
{% extends 'base_html.html' %}
{% block content %}
{% if message != "" %}
<div class="ui success message">
        <div class="header">
            {{ message }}
        </div>
    <p>پیام شما با موفقیت ارسال شد</p>
</div>
{% endif %}
<div class="ui form">
    <form method="post", action="/contact">
        {% csrf_token %}
        <div class="two fields">
            <div class="field">
                <label>عنوان</label>
                <input type="text" name="title" id="id_title" maxlength="40"/>
            </div>
            <div class="field">
                <label>ایمیل</label>
                <input type="email" name="email" id="id_email" maxlength="40"/>
            </div>
        </div>
        <div class="field">
            <label>متن</label>
            <textarea name="text" id="id_text" minlength="10" maxlength="250"></textarea>
        </div>
        <input class="ui submit button" type="submit" value="ارسال پیام" name="submit" id="id_submit"/>
    </form>
</div>
{% endblock %}

templates/editprofile.html
{% extends 'base_html.html' %}
{% block content %}
{% if pass_rematch or email_exists or user_exists %}
<div class="ui negative message">
        <div class="header">
            خطا
        </div>
    <p>
        {% if email_exists %}کاربری با ایمیل وارد شده وجود دارد<br/>{% endif %}
        {% if user_exists %}کاربری با نام کاربری وارد شده وجود دارد<br/>{% endif %}
        {% if pass_rematch %}گذرواژه و تکرار گذرواژه یکسان نیستند{% endif %}
    </p>
</div>
{% endif %}
<div class="ui form">
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field">
            <input type="text" placeholder="نام" value="{{ user.first_name }}" name="first_name" id="id_first_name"/>
        </div>
        <div class="field">
            <input type="text" placeholder="نام خانوادگی" value="{{ user.last_name }}" name="last_name" id="id_last_name"/>
        </div>
        <div class="field">
            <textarea name="bio" placeholder="زندگی نامه" id="id_bio">{{ person.bio }}</textarea><br/>
        </div>
        <div class="field">
            <select name="gender" id="id_gender">
                <option value="M" {% if person.gender == 'M' %} selected {% endif %}>مرد</option>
                <option value="F" {% if person.gender == 'F' %} selected {% endif %}>زن</option>
            </select>
        </div>
        <div class="field">
            <input type="file" id="id_picture" name="picture"/>
        </div>
        <input class="ui submit button" type="submit" value="ویرایش" name="submit" id="id_submit"/>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base_html.html' %}
{% block content %}
<p>سلام. به سامانه استادجو خوش آمدید.</p>
{% if usersSearched %}
    <table class="ui celled table">
        <thead>
            <tr>
                <th>نام کاربری</th>
                <th>نام</th>
                <th>نام خانوادگی</th>
            </tr>
        </thead>
        <tbody>
        <ul>
        {% for record in usersSearched %}
            <div id="id_teacher_{{ forloop.counter0 }}">
                <li data-label="نام کاربری"><a id="id_username" href="/profile/{{ record.username }}">{{ record.username }}</a></li>
                <li data-label="نام" id="id_first_name">{{ record.first_name }}</li>
                <li data-label="نام خانوادگی" id="id_last_name">{{ record.last_name }}</li>
            </div>
{#                        <tr id="id_teacher_{{ forloop.counter0 }}">#}
{#                            <td data-label="نام کاربری"><a id="id_username" href="/profile/{{ record.username }}">{{ record.username }}</a></td>#}
{#                            <td data-label="نام" id="id_first_name">{{ record.first_name }}</td>#}
{#                            <td data-label="نام خانوادگی" id="id_last_name">{{ record.last_name }}</td>#}
{#                        </tr>#}


        {% endfor %}
        </ul>
        </tbody>
    </table>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base_html.html' %}
{% block content %}
{% if error %}
<div class="ui negative message">
        <div class="header">
            خطا
        </div>
    <p>نام کاربری یا گذرواژه غلط است</p>
</div>
{% endif %}
<div class="ui form">
    <form method="post", action=".">
        {% csrf_token %}
        <div class="two fields">
            <div class="field">
                <label>نام کاربری</label>
                <input type="text" name="username" id="id_username"/>
            </div>
            <div class="field">
                <label>رمز عبور</label>
                <input type="password" name="password" id="id_password"/>
            </div>
        </div>
        <input class="ui submit button" type="submit" value="ورود" name="submit" id="id_submit"/>
    </form>
</div>
{% endblock %}

templates/newmeeting.html
{% extends 'base_html.html' %}
{% block content %}
{% if eerror or serror or derror or ebs or tdk%}
<div class="ui negative message">
        <div class="header">
            خطا
        </div>
    <p>
        {% if eerror %}زمان پایان وارد شده معتبر نمی باشد<br/>{% endif %}
        {% if serror %}زمان شروع وارد شده معتبر نمی باشد<br/>{% endif %}
        {% if derror %}تاریخ وارد شده معتبر نمی باشد<br/>{% endif %}
        {% if ebs %}زمان شروع باید قبل از زمان پایان فرصت باشد<br/>{% endif %}
        {% if tdk %}بازه زمانی انتخاب شده با فرصت های قبلی شما اشتراک دارد{% endif %}
    </p>
</div>
{% endif %}
<div class="ui form">
    <form method="post" action=".">
        {% csrf_token %}
        <div class="field">
            <input type="text" placeholder="ظرفیت" name="capacity" id="id_student_capacity"/>
        </div>
        <div class="field">
            <input type="text" placeholder="شروع" name="start" id="id_start"/>
        </div>
        <div class="field">
            <input type="text" name="end" id="id_end" placeholder="پایان"/>
        </div>
        <div class="field">
            <input type="text" name="date" id="id_date" placeholder="تاریخ"/>
        </div>
        <input class="ui submit button" type="submit" value="ایجاد" name="submit" id="id_submit"/>
    </form>
</div>
{% endblock %}

templates/profile.html
{% extends 'base_html.html' %}
{% block content %}
<div class="ui items">
    <div class="item">
        <div class="ui image circular medium">
            <img id="id_picture" src="/{{ person.picture }}">
        </div>
        <div class="content">
            <a class="header"><b id="id_first_name">{{ user.first_name }}</b><b id="id_last_name">{{ user.last_name }}</b></a>
            <div class="meta">
                <span><b id="id_username">{{ user.username }}</b> / {% if person.gender == 'M' %}مرد{% else %}زن{% endif %}</span>
            </div>
            <div class="description">
                <p>
                    {% if user.is_authenticated %}شما به عنوان {{ group }} وارد شده اید{% endif %}
                </p>
                <a id="id_remove_user" href="/removeuser">حذف حساب کاربری</a>
            </div>
            <div class="extra">
{#                {% load markup_tags %}#}
{#                {{ entry.content|apply_markup:"markdown" }}#}
{#                {{ person.bio|apply_markup:"markdown" }}#}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base_html.html' %}
{% block content %}
{% if pass_rematch or email_exists or user_exists %}
<div class="ui negative message">
        <div class="header">
            خطا
        </div>
    <p>
        {% if email_exists %}کاربری با ایمیل وارد شده وجود دارد<br/>{% endif %}
        {% if user_exists %}کاربری با نام کاربری وارد شده وجود دارد<br/>{% endif %}
        {% if pass_rematch %}گذرواژه و تکرار گذرواژه یکسان نیستند{% endif %}
    </p>
</div>
{% endif %}
<div class="ui form">
    <form method="post" action=".">
        {% csrf_token %}
        <div class="field">
            <input type="text" placeholder="نام" name="first_name" id="id_first_name"/>
        </div>
        <div class="field">
            <input type="text" placeholder="نام خانوادگی" name="last_name" id="id_last_name"/>
        </div>
        <div class="field{% if email_exists %} error{% endif %}">
            <input type="email" placeholder="ایمیل" name="email" id="id_email"/>
        </div>
        <div class="field{% if user_exists %} error{% endif %}">
            <input type="text" placeholder="نام کاربری" name="username" id="id_username"/>
        </div>
        <div class="field">
            <input type="password" placeholder="رمز عبور" name="password1" id="id_password1"/>
        </div>
        <div class="field{% if pass_rematch %} error{% endif %}">
            <input type="password" placeholder="تکرار رمز عبور" name="password2" id="id_password2"/>
        </div>
        <div class="grouped fields">
            <label>ثبت نام به عنوان</label>
            <div class="field">
                <div class="ui slider checkbox">
                    <input type="radio" name="group" id="id_type_1" value="استاد" checked="checked"/>
                    <label>استاد</label>
                </div>
            </div>
            <div class="field">
                <div class="ui slider checkbox">
                    <input type="radio" name="group" id="id_type_0" value="دانشجو"/>
                    <label>دانشجو</label>
                </div>
            </div>
        </div>
        <input class="ui submit button" type="submit" value="ثبت نام" name="submit" id="id_submit"/>
    </form>
</div>
{% endblock %}